services:
  web1:
    image: nginxdemos/hello
    networks:
      - lbnet

  web2:
    image: nginxdemos/hello
    networks:
      - lbnet

  web3:
    image: nginxdemos/hello
    networks:
      - lbnet

  nginx-lb:
    build: ./nginx
    ports:
      - "8080:80"
    networks:
      - lbnet
    depends_on:
      - web1
      - web2
      - web3

  haproxy-lb:
    build: ./haproxy
    ports:
      - "8081:80"
    networks:
      - lbnet
    depends_on:
      - web1
      - web2
      - web3

  apache-lb:
    build: ./apache
    ports:
      - "8082:80"
    networks:
      - lbnet
    depends_on:
      - web1
      - web2
      - web3

networks:
  lbnet: