version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: os_compare
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  # Mount init script
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16  # PostgreSQL 16 mới nhất
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: os_compare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d os_compare"]
      interval: 10s
      timeout: 5s
      retries: 5

  mariadb:
    image: mariadb:11.3  # MariaDB 11 mới nhất
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: os_compare
      MYSQL_USER: mariadb_user
      MYSQL_PASSWORD: mariadb_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mariadb_user", "-pmariadb_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra:
    image: cassandra:5.0  # Cassandra 5.0 mới nhất
    container_name: cassandra-db
    restart: always
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./init-scripts:/init-scripts
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-init:
    image: cassandra:5.0
    depends_on:
      cassandra:
        condition: service_healthy
    command: >
      bash -c "
        echo 'Waiting for Cassandra to be ready...' && 
        sleep 5 &&
        echo 'Creating keyspace only...' &&
        cqlsh cassandra-db -e \"CREATE KEYSPACE IF NOT EXISTS mykeyspace WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };\" &&
        echo 'Keyspace created successfully!'"
    networks:
      - default

volumes:
  mongodb_data:
  postgres_data:
  mariadb_data:
  cassandra-data: