version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: os_compare  # This will create the os_compare database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d os_compare"]
      interval: 10s
      timeout: 5s
      retries: 5

  mariadb:
    image: mariadb:10.10
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: os_compare  # This will create the os_compare database
      MYSQL_USER: mariadb_user
      MYSQL_PASSWORD: mariadb_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mariadb_user", "-pmariadb_password"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mariadb_data: